[package]
    edition = "2021"
    name    = "altgetset"
    version = "0.1.0"

[lib]
    proc-macro = true

[dependencies]
    proc-macro-error2 = "2"
    proc-macro2       = "1"
    quote             = "1"
    syn               = "2"
